#!/usr/bin/env node
/**
 * Re-enrich existing leads with improved water feature detection (no full re-scrape)
 * Usage: node enrich-water.js [--input clearwater-leads.json] [--export-app]
 */

const fs = require('fs');
const { getWaterFeatures } = require('./scraper/water-features');
const { scoreLead } = require('./scraper/scoring');

async function main() {
  const args = process.argv.slice(2);
  let input = 'clearwater-leads.json';
  let exportApp = false;

  for (let i = 0; i < args.length; i += 1) {
    if (args[i] === '--input' && args[i + 1]) input = args[++i];
    if (args[i] === '--export-app') exportApp = true;
  }

  const leads = JSON.parse(fs.readFileSync(input, 'utf8'));
  console.log(`Enriching water features for ${leads.length} leads...`);

  let withWater = 0;
  for (let i = 0; i < leads.length; i += 1) {
    const lead = leads[i];
    process.stdout.write(`\r  ${i + 1}/${leads.length}`);

    if (!lead.lat || !lead.lng) continue;

    const water = await getWaterFeatures(lead.lat, lead.lng);
    lead.waterFeatures = water.features;
    lead.waterFeatureSources = water.sources;
    lead.waterFeatureDetails = water.details;

    if (water.features.length) withWater += 1;

    const { score, breakdown } = scoreLead(lead);
    lead.score = score;
    lead.scoreBreakdown = breakdown;
  }

  process.stdout.write('\n');
  leads.sort((a, b) => b.score - a.score || a.landValue - b.landValue);
  leads.forEach((lead, idx) => { lead.id = idx + 1; });

  fs.writeFileSync(input, JSON.stringify(leads, null, 2));
  console.log(`✅ Updated ${input} — ${withWater}/${leads.length} leads have water features`);

  if (exportApp) {
    const code = `// Auto-generated by enrich-water.js\nconst leadData = ${JSON.stringify(leads, null, 2)};\n\ndocument.addEventListener('DOMContentLoaded', () => {\n  if (typeof prospects !== 'undefined') {\n    prospects = leadData;\n    if (typeof loadSaved === 'function') loadSaved();\n    if (typeof buildLeadFilters === 'function') buildLeadFilters();\n    if (typeof loadParcelBoundaries === 'function') loadParcelBoundaries(prospects);\n  }\n});\n`;
    fs.writeFileSync('leads-data.js', code);
    console.log('✅ Wrote leads-data.js');
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});