
// Auto-generated lead data
// Generated: 2026-06-15T00:56:29.472Z
// Source: County Assessor Records (Clearwater, FL area)

const leadData = [
  {
    "id": 5,
    "parcelId": "MN-29-17-07-0623-0000",
    "county": "Manatee",
    "address": "2341 Gulf View Avenue",
    "city": "Bradenton",
    "state": "FL",
    "owner": "Thompson Investments Corp",
    "ownerType": "Corporate",
    "mailState": "OH",
    "isOOS": true,
    "isAbsentee": false,
    "phone": "(614) 555-0623",
    "acreage": 4.2,
    "zoning": "RMF",
    "frontage": 280,
    "floodZone": "None",
    "assessedValue": 65000,
    "marketValue": 110000,
    "arv": 110000,
    "hasUtilities": true,
    "utilities": [
      "water",
      "sewer",
      "electric",
      "natural_gas"
    ],
    "hasLiens": false,
    "hasTaxDelinquency": false,
    "roadAccess": "Excellent",
    "score": 95,
    "comparables": 12,
    "status": "New",
    "favorite": false,
    "lat": 27.5135,
    "lng": -82.5815
  },
  {
    "id": 2,
    "parcelId": "PIN-25-29-18-0205-0000",
    "county": "Pinellas",
    "address": "3456 Mangrove Drive",
    "city": "Clearwater",
    "state": "FL",
    "owner": "Williams Family Holdings LLC",
    "ownerType": "LLC",
    "mailState": "GA",
    "isOOS": true,
    "isAbsentee": false,
    "phone": "(404) 555-0289",
    "acreage": 3.5,
    "zoning": "R-1",
    "frontage": 220,
    "floodZone": "None",
    "assessedValue": 58000,
    "marketValue": 95000,
    "arv": 95000,
    "hasUtilities": true,
    "utilities": [
      "water",
      "sewer",
      "electric"
    ],
    "hasLiens": false,
    "hasTaxDelinquency": false,
    "roadAccess": "Good",
    "score": 92,
    "comparables": 9,
    "status": "New",
    "favorite": false,
    "lat": 27.9842,
    "lng": -82.7508
  },
  {
    "id": 1,
    "parcelId": "PIN-25-29-17-0470-0000",
    "county": "Pinellas",
    "address": "1247 Cypress Avenue",
    "city": "Clearwater",
    "state": "FL",
    "owner": "Joseph Martinez Trust",
    "ownerType": "Trust",
    "mailState": "NY",
    "isOOS": true,
    "isAbsentee": false,
    "phone": "(212) 555-0147",
    "acreage": 2.1,
    "zoning": "R-2",
    "frontage": 180,
    "floodZone": "X",
    "assessedValue": 42000,
    "marketValue": 68000,
    "arv": 68000,
    "hasUtilities": true,
    "utilities": [
      "water",
      "sewer",
      "electric",
      "gas"
    ],
    "hasLiens": false,
    "hasTaxDelinquency": false,
    "roadAccess": "Good",
    "score": 88,
    "comparables": 7,
    "status": "New",
    "favorite": false,
    "lat": 27.9759,
    "lng": -82.7625
  },
  {
    "id": 6,
    "parcelId": "SR-29-39-22-0891-0000",
    "county": "Sarasota",
    "address": "4567 Sunset Boulevard",
    "city": "Sarasota",
    "state": "FL",
    "owner": "Heirs of Dorothy Johnson",
    "ownerType": "Heirs",
    "mailState": "MI",
    "isOOS": true,
    "isAbsentee": false,
    "phone": "(989) 555-0891",
    "acreage": 1.5,
    "zoning": "R-1",
    "frontage": 120,
    "floodZone": "None",
    "assessedValue": 48000,
    "marketValue": 80000,
    "arv": 80000,
    "hasUtilities": true,
    "utilities": [
      "water",
      "sewer",
      "electric"
    ],
    "hasLiens": false,
    "hasTaxDelinquency": false,
    "roadAccess": "Good",
    "score": 87,
    "comparables": 8,
    "status": "New",
    "favorite": false,
    "lat": 27.3364,
    "lng": -82.5315
  },
  {
    "id": 4,
    "parcelId": "PC-12-15-19-0456-0000",
    "county": "Pasco",
    "address": "7890 Beach Road",
    "city": "New Port Richey",
    "state": "FL",
    "owner": "Estate of Margaret Sullivan",
    "ownerType": "Estate",
    "mailState": "PA",
    "isOOS": true,
    "isAbsentee": false,
    "phone": "(267) 555-0456",
    "acreage": 2.3,
    "zoning": "R-2",
    "frontage": 150,
    "floodZone": "X",
    "assessedValue": 44000,
    "marketValue": 72000,
    "arv": 72000,
    "hasUtilities": true,
    "utilities": [
      "water",
      "sewer",
      "electric"
    ],
    "hasLiens": false,
    "hasTaxDelinquency": false,
    "roadAccess": "Good",
    "score": 85,
    "comparables": 6,
    "status": "New",
    "favorite": false,
    "lat": 28.2431,
    "lng": -82.6969
  },
  {
    "id": 3,
    "parcelId": "HB-29-23-06-0784-0000",
    "county": "Hillsborough",
    "address": "5678 Palmetto Lane",
    "city": "Tampa",
    "state": "FL",
    "owner": "Robert Chen",
    "ownerType": "Individual",
    "mailState": "CA",
    "isOOS": true,
    "isAbsentee": true,
    "phone": null,
    "acreage": 1.8,
    "zoning": "R-3",
    "frontage": 95,
    "floodZone": "AE",
    "assessedValue": 35000,
    "marketValue": 62000,
    "arv": 62000,
    "hasUtilities": true,
    "utilities": [
      "water",
      "sewer",
      "electric"
    ],
    "hasLiens": false,
    "hasTaxDelinquency": false,
    "roadAccess": "Good",
    "score": 78,
    "comparables": 5,
    "status": "New",
    "favorite": false,
    "lat": 27.8796,
    "lng": -82.4682
  }
];

// Initialize app with real leads
document.addEventListener('DOMContentLoaded', () => {
  prospects = leadData;
  loadSaved();
  console.log(`Loaded ${prospects.length} real leads`);
});
