// redact-leads.js — produce a deploy-safe leads-data.js for the public demo.
//
// The demo "lock" (50 unlocked individual-owner leads, everything else locked)
// is the only thing standing between a prospect and the full contact database.
// Hiding contacts in the UI is not enough: leads-data.js is shipped verbatim to
// the browser, so any locked lead that still carries phone/email leaks via View
// Source or the DevTools console.
//
// This script strips every contact field from locked leads at BUILD time, so the
// served leads-data.js physically does not contain locked PII. The full,
// un-redacted master is backed up to data/leads-data.full.js (gitignored) so the
// real contacts are never lost.
//
// Run:  node redact-leads.js          (no system node — use Playwright's bundle)
//
// The unlock selection below is a byte-for-byte mirror of the runtime logic in
// index.html (loadRealLeads). If you change one, change both.

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'leads-data.js');
const MASTER = path.join(__dirname, 'data', 'leads-data.full.js');
const DEMO_UNLOCK_LIMIT = 50;

// Contact-derived fields that must never reach a locked lead in the browser.
// Owner name, mailing address and parcel id are public county records and the
// UI shows them even while locked, so they are intentionally NOT stripped.
const CONTACT_FIELDS = [
  'phone', 'email', 'phones', 'emails',
  'phoneType', 'phoneScore',
  'skiptraceSource', 'skiptraceName', 'skiptraceStatus', 'skiptracedAt',
  'spokeoId', 'spokeoMatchType', 'spokeoOwnerName',
];

function parseLeadData(src) {
  const m = src.match(/const leadData\s*=\s*(\[[\s\S]*?\]);/);
  if (!m) throw new Error('Could not find `const leadData = [...]` in leads-data.js');
  let leadData;
  eval('leadData = ' + m[1]); // trusted local build artifact
  if (!Array.isArray(leadData)) throw new Error('leadData is not an array');
  return leadData;
}

function computeUnlocked(prospects) {
  // Mirror of index.html loadRealLeads(): top N individual owners by score,
  // tie-broken by original array position.
  return new Set(
    prospects
      .map((p, i) => ({ p, i }))
      .filter(({ p }) => p.ownerType === 'Individual')
      .sort((a, b) => (b.p.score - a.p.score) || (a.i - b.i))
      .slice(0, DEMO_UNLOCK_LIMIT)
      .map(({ p }) => p)
  );
}

function main() {
  const src = fs.readFileSync(SRC, 'utf8');
  const leadData = parseLeadData(src);

  // Back up the un-redacted master once per run (gitignored, local-only).
  fs.mkdirSync(path.dirname(MASTER), { recursive: true });
  fs.writeFileSync(MASTER, src, 'utf8');

  const unlocked = computeUnlocked(leadData);
  let stripped = 0;
  let strippedFields = 0;

  const redacted = leadData.map(p => {
    const out = { ...p };
    if (unlocked.has(p)) {
      out.isLocked = false;
      return out;
    }
    out.isLocked = true;
    for (const f of CONTACT_FIELDS) {
      if (out[f] !== undefined && out[f] !== null &&
          !(Array.isArray(out[f]) && out[f].length === 0)) {
        strippedFields++;
      }
      delete out[f];
    }
    stripped++;
    return out;
  });

  const header =
    '// Auto-generated by scrape-leads.js, redacted by redact-leads.js\n' +
    '// Locked-lead contact data (phone/email/skiptrace) is stripped at build\n' +
    '// time — full master lives in data/leads-data.full.js (gitignored).\n' +
    `// Redacted ${stripped} locked leads, ${unlocked.size} unlocked.\n\n`;

  const body = 'const leadData = ' + JSON.stringify(redacted, null, 2) + ';\n';
  fs.writeFileSync(SRC, header + body, 'utf8');

  // Verify: no contact PII survives on any locked lead.
  const check = parseLeadData(fs.readFileSync(SRC, 'utf8'));
  const leaks = check.filter(p => p.isLocked &&
    CONTACT_FIELDS.some(f => p[f] != null && !(Array.isArray(p[f]) && p[f].length === 0)));

  console.log(`Master backed up    -> ${path.relative(__dirname, MASTER)}`);
  console.log(`Total leads         : ${redacted.length}`);
  console.log(`Unlocked (demo)     : ${unlocked.size}`);
  console.log(`Locked & redacted   : ${stripped}`);
  console.log(`Contact fields wiped: ${strippedFields}`);
  console.log(`Leaked locked leads : ${leaks.length} ${leaks.length === 0 ? '✓' : '✗ FAIL'}`);
  if (leaks.length) process.exit(1);
}

main();
