#!/usr/bin/env node
/**
 * Skiptrace all leads via Spokeo Business API (+ optional proxy)
 *
 * Setup:
 *   cp .env.example .env
 *   # add SPOKEO_API_KEY to .env
 *
 * Usage:
 *   node skiptrace-leads.js --export-app
 *   node skiptrace-leads.js --limit 50 --export-app
 *   node skiptrace-leads.js --force --export-app   # re-run even if phone exists
 */

const fs = require('fs');
const path = require('path');
const { loadEnvFile } = require('./scraper/load-env');
const { createSkiptraceProvider, skiptraceConfigHelp } = require('./scraper/skiptrace');
const { getProxyUrl } = require('./scraper/skiptrace/proxy-fetch');
const { scoreLead } = require('./scraper/scoring');

loadEnvFile();

function parseArgs(argv) {
  const options = {
    input: 'clearwater-leads.json',
    output: 'clearwater-leads.json',
    limit: null,
    exportApp: false,
    skipExisting: true,
    minScore: null,
    checkpointEvery: 25,
    exportCsv: true
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--input' && argv[i + 1]) options.input = argv[++i];
    else if (arg === '--output' && argv[i + 1]) options.output = argv[++i];
    else if (arg === '--limit' && argv[i + 1]) options.limit = Number(argv[++i]);
    else if (arg === '--min-score' && argv[i + 1]) options.minScore = Number(argv[++i]);
    else if (arg === '--checkpoint' && argv[i + 1]) options.checkpointEvery = Number(argv[++i]);
    else if (arg === '--export-app') options.exportApp = true;
    else if (arg === '--no-csv') options.exportCsv = false;
    else if (arg === '--force') options.skipExisting = false;
    else if (arg === '--help') {
      console.log(`
Skiptrace leads with Spokeo API + optional proxy

Options:
  --input FILE        Input JSON (default: clearwater-leads.json)
  --output FILE       Output JSON (default: same as input)
  --limit N           Only process first N leads needing skiptrace
  --min-score N       Only skiptrace leads with score >= N
  --checkpoint N      Save progress every N leads (default: 25)
  --export-app        Regenerate leads-data.js
  --no-csv            Skip contacts CSV export
  --force             Re-skiptrace even if phone already present
  --help              Show Spokeo env configuration

${skiptraceConfigHelp()}
`);
      process.exit(0);
    }
  }

  return options;
}

function applyContactToLead(lead, contact) {
  const now = new Date().toISOString();
  if (!contact) {
    lead.skiptraceStatus = 'no_match';
    lead.skiptracedAt = now;
    return false;
  }

  lead.phone = contact.phone || lead.phone || null;
  lead.phones = contact.phones?.length ? contact.phones : (lead.phone ? [lead.phone] : []);
  lead.email = contact.email || lead.email || null;
  lead.emails = contact.emails?.length ? contact.emails : (lead.email ? [lead.email] : []);
  lead.isDNC = contact.isDNC ?? lead.isDNC ?? false;
  lead.phoneType = contact.phoneType || lead.phoneType || null;
  lead.skiptraceSource = contact.skiptraceSource || 'spokeo';
  lead.spokeoId = contact.spokeoId || null;
  lead.spokeoMatchType = contact.spokeoMatchType || null;
  lead.spokeoOwnerName = contact.spokeoOwnerName || null;
  lead.skiptraceStatus = (lead.phone || lead.email) ? 'matched' : 'no_match';
  lead.skiptracedAt = now;
  return !!(lead.phone || lead.email);
}

function exportForApp(leads) {
  const code = `// Auto-generated by skiptrace-leads.js\nconst leadData = ${JSON.stringify(leads, null, 2)};\n`;
  fs.writeFileSync('leads-data.js', code);
}

function exportContactsCsv(leads, filePath) {
  const headers = [
    'id', 'parcelId', 'owner', 'ownerType', 'county', 'mailingAddress',
    'phone', 'phones', 'email', 'emails', 'isDNC', 'skiptraceStatus',
    'spokeoMatchType', 'score'
  ];
  const rows = leads.map((l) => [
    l.id,
    l.parcelId,
    l.owner,
    l.ownerType,
    l.county,
    typeof l.mailingAddress === 'string' ? l.mailingAddress : l.mailingAddress?.full || '',
    l.phone || '',
    (l.phones || []).join('; '),
    l.email || '',
    (l.emails || []).join('; '),
    l.isDNC ? 'yes' : 'no',
    l.skiptraceStatus || '',
    l.spokeoMatchType || '',
    l.score
  ]);
  const csv = [headers.join(','), ...rows.map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(','))].join('\n');
  fs.writeFileSync(filePath, csv);
}

function saveLeads(leads, outputPath) {
  fs.writeFileSync(outputPath, JSON.stringify(leads, null, 2));
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const skiptrace = createSkiptraceProvider();

  if (!skiptrace) {
    console.error('❌ Spokeo not configured.');
    console.error('   Copy .env.example → .env and set SPOKEO_API_KEY');
    console.error(skiptraceConfigHelp());
    process.exit(1);
  }

  if (!fs.existsSync(options.input)) {
    console.error(`❌ Input file not found: ${options.input}`);
    process.exit(1);
  }

  const leads = JSON.parse(fs.readFileSync(options.input, 'utf8'));
  let targets = leads.filter((lead) => {
    if (options.minScore != null && lead.score < options.minScore) return false;
    if (options.skipExisting && lead.phone) return false;
    return true;
  });

  if (options.limit) targets = targets.slice(0, options.limit);

  const delayMs = Number(process.env.SPOKEO_DELAY_MS || 600);
  const estMin = Math.ceil((targets.length * delayMs) / 60000);

  console.log(`\n📞 Skiptracing ${targets.length} / ${leads.length} leads via Spokeo`);
  console.log(`   Proxy: ${getProxyUrl() || 'none (direct)'}`);
  console.log(`   Est. runtime: ~${estMin} min at ${delayMs}ms/call\n`);

  let hits = 0;
  let misses = 0;
  let errors = 0;

  for (let i = 0; i < targets.length; i += 1) {
    const lead = targets[i];
    const label = `${lead.owner.slice(0, 32)} · ${lead.parcelId}`;
    process.stdout.write(`\r  [${i + 1}/${targets.length}] ${label.padEnd(48)}`);

    try {
      const contact = await skiptrace.enrich(lead);
      const matched = applyContactToLead(lead, contact);
      const { score, breakdown } = scoreLead(lead);
      lead.score = score;
      lead.scoreBreakdown = breakdown;
      if (matched) hits += 1;
      else misses += 1;
    } catch (error) {
      errors += 1;
      lead.skiptraceStatus = 'error';
      lead.skiptraceError = error.message;
      lead.skiptracedAt = new Date().toISOString();
      console.warn(`\n  ⚠️  ${lead.parcelId}: ${error.message}`);
    }

    if (options.checkpointEvery > 0 && (i + 1) % options.checkpointEvery === 0) {
      saveLeads(leads, options.output);
      process.stdout.write(' 💾');
    }
  }

  process.stdout.write('\n');
  leads.sort((a, b) => b.score - a.score || a.landValue - b.landValue);
  leads.forEach((lead, idx) => { lead.id = idx + 1; });

  saveLeads(leads, options.output);

  const totalPhones = leads.filter((l) => l.phone).length;
  const totalEmails = leads.filter((l) => l.email).length;
  const matched = leads.filter((l) => l.skiptraceStatus === 'matched').length;

  console.log('\n' + '='.repeat(60));
  console.log('✅ Skiptrace complete');
  console.log(`   This run: ${hits} matched, ${misses} no match, ${errors} errors`);
  console.log(`   Total with phone: ${totalPhones}/${leads.length}`);
  console.log(`   Total with email: ${totalEmails}/${leads.length}`);
  console.log(`   Marked matched:   ${matched}`);
  console.log(`   Saved → ${options.output}`);
  console.log('='.repeat(60));

  if (options.exportCsv) {
    const csvPath = path.join(path.dirname(options.output) || '.', 'skiptrace-contacts.csv');
    exportContactsCsv(leads, csvPath);
    console.log(`✅ Wrote ${csvPath}`);
  }

  if (options.exportApp) {
    exportForApp(leads);
    console.log('✅ Wrote leads-data.js');
  }
}

main().catch((err) => {
  console.error('❌', err.message);
  process.exit(1);
});