#!/usr/bin/env node
/**
 * Skiptrace existing leads via Spokeo Business API (+ optional proxy)
 *
 * Usage:
 *   export CONTACT_PROVIDER=spokeo
 *   export SPOKEO_API_KEY=your_key
 *   export SPOKEO_PROXY_URL=http://user:pass@proxy:port   # optional
 *   node skiptrace-leads.js --limit 50 --export-app
 */

const fs = require('fs');
const { createSkiptraceProvider, skiptraceConfigHelp } = require('./scraper/skiptrace');
const { getProxyUrl } = require('./scraper/skiptrace/proxy-fetch');
const { scoreLead } = require('./scraper/scoring');

function parseArgs(argv) {
  const options = {
    input: 'clearwater-leads.json',
    output: 'clearwater-leads.json',
    limit: null,
    exportApp: false,
    skipExisting: true,
    minScore: null
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--input' && argv[i + 1]) options.input = argv[++i];
    else if (arg === '--output' && argv[i + 1]) options.output = argv[++i];
    else if (arg === '--limit' && argv[i + 1]) options.limit = Number(argv[++i]);
    else if (arg === '--min-score' && argv[i + 1]) options.minScore = Number(argv[++i]);
    else if (arg === '--export-app') options.exportApp = true;
    else if (arg === '--force') options.skipExisting = false;
    else if (arg === '--help') {
      console.log(`
Skiptrace leads with Spokeo API + optional proxy

Options:
  --input FILE     Input JSON (default: clearwater-leads.json)
  --output FILE    Output JSON (default: same as input)
  --limit N        Only process first N leads needing skiptrace
  --min-score N    Only skiptrace leads with score >= N
  --export-app     Regenerate leads-data.js
  --force          Re-skiptrace even if phone already present
  --help           Show Spokeo env configuration

${skiptraceConfigHelp()}
`);
      process.exit(0);
    }
  }

  return options;
}

function exportForApp(leads) {
  const code = `// Auto-generated by skiptrace-leads.js\nconst leadData = ${JSON.stringify(leads, null, 2)};\n\ndocument.addEventListener('DOMContentLoaded', () => {\n  if (typeof prospects !== 'undefined') {\n    prospects = leadData;\n    if (typeof loadSaved === 'function') loadSaved();\n    if (typeof buildLeadFilters === 'function') buildLeadFilters();\n    if (typeof loadParcelBoundaries === 'function') loadParcelBoundaries(prospects);\n  }\n});\n`;
  fs.writeFileSync('leads-data.js', code);
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const skiptrace = createSkiptraceProvider();

  if (!skiptrace) {
    console.error('❌ Spokeo not configured. Set CONTACT_PROVIDER=spokeo and SPOKEO_API_KEY');
    console.error(skiptraceConfigHelp());
    process.exit(1);
  }

  const leads = JSON.parse(fs.readFileSync(options.input, 'utf8'));
  let targets = leads.filter((lead) => {
    if (options.minScore != null && lead.score < options.minScore) return false;
    if (options.skipExisting && lead.phone) return false;
    return true;
  });

  if (options.limit) targets = targets.slice(0, options.limit);

  console.log(`\n📞 Skiptracing ${targets.length} leads via Spokeo`);
  console.log(`   Proxy: ${getProxyUrl() || 'none (direct)'}\n`);

  let hits = 0;
  let misses = 0;

  for (let i = 0; i < targets.length; i += 1) {
    const lead = targets[i];
    process.stdout.write(`\r  ${i + 1}/${targets.length} — ${lead.owner.slice(0, 28).padEnd(28)}`);

    try {
      const contact = await skiptrace.enrich(lead);
      if (contact?.phone || contact?.email) {
        lead.phone = contact.phone || lead.phone;
        lead.email = contact.email || lead.email;
        lead.skiptraceSource = contact.skiptraceSource || 'spokeo';
        lead.spokeoId = contact.spokeoId || null;
        lead.spokeoMatchType = contact.spokeoMatchType || null;
        const { score, breakdown } = scoreLead(lead);
        lead.score = score;
        lead.scoreBreakdown = breakdown;
        hits += 1;
      } else {
        misses += 1;
      }
    } catch (error) {
      misses += 1;
      console.warn(`\n  ⚠️  ${lead.parcelId}: ${error.message}`);
    }
  }

  process.stdout.write('\n');
  leads.sort((a, b) => b.score - a.score || a.landValue - b.landValue);
  leads.forEach((lead, idx) => { lead.id = idx + 1; });

  fs.writeFileSync(options.output, JSON.stringify(leads, null, 2));

  const totalPhones = leads.filter((l) => l.phone).length;
  console.log('\n' + '='.repeat(60));
  console.log(`✅ Skiptrace complete`);
  console.log(`   This run: ${hits} matched, ${misses} no match`);
  console.log(`   Total leads with phone: ${totalPhones}/${leads.length}`);
  console.log(`   Saved → ${options.output}`);
  console.log('='.repeat(60));

  if (options.exportApp) {
    exportForApp(leads);
    console.log('✅ Wrote leads-data.js');
  }
}

main().catch((err) => {
  console.error('❌', err.message);
  process.exit(1);
});