#!/usr/bin/env bash
# Stage the clean, PII-free East Florida (ZIP 32137 / Palm Coast / Flagler)
# baseline from this repo's current checkout, with a single clean commit and
# no PII in history. Run from a checkout of urthmapper on the branch that has
# the latest app (includes the natural-language Deal Finder).
#
# Usage:
#   tools/stage-eastflorida.sh [OUT_DIR]
#   git -C OUT_DIR remote add origin <urthmapper32137 git url>
#   git -C OUT_DIR push -u origin main
set -euo pipefail
SRC="$(git rev-parse --show-toplevel)"
OUT="${1:-/tmp/urthmapper-eastflorida}"
rm -rf "$OUT"; mkdir -p "$OUT"
# Copy tracked files only (no .git history) at current HEAD -> latest app.
git -C "$SRC" archive HEAD | tar -x -C "$OUT"
cd "$OUT"
# Drop region PII, generated lead data, and junk probe files.
rm -f leads-data.js clearwater-leads.json clearwater-leads.geojson clearwater-leads.csv \
      clearwater-leads-summary.md urthmapper-leads.csv \
      data/pinellas_clearwater_vacant_leads.geojson data/pinellas_vacant_leads.csv \
      _10k_test_delete_me.txt _5k_embed_probe.txt _mcp_test.txt _push_test_delete_me.txt \
      _size_probe.txt mcp-test.txt size-test.txt 2>/dev/null || true
rmdir data 2>/dev/null || true
# Retarget the README for East Florida / no-data state.
cat > README.md <<'MD'
# urthmapper — East Florida

Vacant land prospect pipeline for **East Florida (ZIP 32137 / Palm Coast / Flagler County)**.
Scrapes county GIS + FEMA flood + OSM, ranks parcels by seller motivation, and serves an
interactive map with a natural-language Deal Finder.

Clean clone of the urthmapper app with **no lead data included** — all leads come from running
the scraper against live public records. The UI shows a "no data" banner until `leads-data.js`
is generated by a scrape.

## Generate real leads
```bash
# needs outbound network to county GIS + hazards.fema.gov + OSM,
# and a skip-trace key (SPOKEO_API_KEY) for phone/email
node scrape-leads.js --export-app
```
See `DATA_INTEGRATION_GUIDE.md`. Flagler County / 32137 source still needs wiring in.
MD
# Fresh single-commit history (no PII anywhere in history).
git init -q -b main
git add -A
git commit -q -m "urthmapper — East Florida (32137) baseline" >/dev/null
echo "Clean baseline staged at: $OUT"
echo "Files: $(git ls-files | wc -l | tr -d ' ')   (PII/junk removed, single clean commit)"
echo "Next: git -C \"$OUT\" remote add origin <urthmapper32137 url> && git -C \"$OUT\" push -u origin main"
